// flow-typed signature: f40133a2711406d59b4176d0c69b824e
// flow-typed version: <<STUB>>/lodash.isnan_v^3.0.2/flow_v0.67.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'lodash.isnan'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'lodash.isnan' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'lodash.isnan/index' {
  declare module.exports: $Exports<'lodash.isnan'>;
}
declare module 'lodash.isnan/index.js' {
  declare module.exports: $Exports<'lodash.isnan'>;
}
