// flow-typed signature: 91546607045315f912857b41155dc0ab
// flow-typed version: <<STUB>>/lodash.isempty_v^4.4.0/flow_v0.67.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'lodash.isempty'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'lodash.isempty' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'lodash.isempty/index' {
  declare module.exports: $Exports<'lodash.isempty'>;
}
declare module 'lodash.isempty/index.js' {
  declare module.exports: $Exports<'lodash.isempty'>;
}
