// flow-typed signature: 53380ed328208f163677d15c78d29657
// flow-typed version: <<STUB>>/lodash.isstring_v^4.0.1/flow_v0.67.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'lodash.isstring'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'lodash.isstring' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'lodash.isstring/index' {
  declare module.exports: $Exports<'lodash.isstring'>;
}
declare module 'lodash.isstring/index.js' {
  declare module.exports: $Exports<'lodash.isstring'>;
}
